<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0-windows</TargetFramework>
    <AssemblyName>ss</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIconCondition Condition="Exists('..\app.ico')">..\app.ico</ApplicationIconCondition>
  </PropertyGroup>

</Project>
